version: '3'

services:
  bot:
    build:
      context: ./bot
    restart: unless-stopped
  api:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - 3001
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017
